;This file contains references to people who contributed to the software.
;Schema: "[Name](Reference)" = Info
;Where:
;  * Name: username, first/lastname
;  * Reference: E-mail/webpage
;  * Info: Information about / kind of contribution
;You can provide it to be shown here on an opt-in basis after contributing this project.

;LIST OF CONTRIBUTORS
"[蓝点lilac](tencent://message/?uin=1617859183)" = Main developer
"[Li Guanglin](https://github.com/guanglinn)" = Current developer
